version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/app'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/app'
    schedule:
      interval: 'daily'
      
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    directory: '/web'
    schedule:
      interval: 'daily'
