version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/app'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'docker'
    directory: '/app'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'docker'
    directory: '/web'
    schedule:
      interval: 'weekly'
