version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    image: steam-trader_app:2.1.1
    env_file:
      - ./app/.env
    volumes:
      - ./app/output:/usr/app/output
      - ./app/config:/usr/app/config
    ports:
      - 1228:1228

  web:
    depends_on:
      - app
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    image: steam-trader_web:2.1.1
    env_file:
      - ./web/.env
    ports:
      - 1227:1227
