version: '3'
services:
  app:
    build: ./app
    env_file:
      - ./app/.env
    volumes:
      - ./app/output:/usr/app/output
    ports:
      - 1228:1228
  web:
    build: ./web
    env_file:
      - ./web/.env
    ports:
      - 1227:1227
